# Generated by Django 6.0.3 on 2026-04-05 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('community', models.CharField(choices=[('ANDALUCIA', 'Andalucía'), ('ARAGON', 'Aragón'), ('ASTURIAS', 'Asturias'), ('BALEARES', 'Islas Baleares'), ('CANARIAS', 'Canarias'), ('CANTABRIA', 'Cantabria'), ('CASTILLA_LA_MANCHA', 'Castilla-La Mancha'), ('CASTILLA_Y_LEON', 'Castilla y León'), ('CATALUNYA', 'Cataluña'), ('COMUNITAT_VALENCIANA', 'Comunidad Valenciana'), ('EXTREMADURA', 'Extremadura'), ('GALICIA', 'Galicia'), ('MADRID', 'Comunidad de Madrid'), ('MURCIA', 'Región de Murcia'), ('NAVARRA', 'Navarra'), ('PAIS_VASCO', 'País Vasco'), ('LA_RIOJA', 'La Rioja'), ('CEUTA', 'Ceuta'), ('MELILLA', 'Melilla')], default='MADRID', max_length=50)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('annual_sales', models.FloatField(blank=True, null=True)),
                ('square_meters', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RESERVED', 'Reservada'), ('SOLD', 'Vendida')], default='AVAILABLE', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Administración',
                'verbose_name_plural': 'Administraciones',
                'db_table': 'administrations',
                'ordering': ['-created_date'],
            },
        ),
    ]
