# Generated by Django 6.0.3 on 2026-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('interes', models.CharField(choices=[('integral', 'Traspaso Administración Integral'), ('mixto', 'Punto de Venta Mixto'), ('asesoria', 'Asesoría Jurídica / Fiscal')], max_length=20, verbose_name='Tipo de activo de interés')),
                ('mensaje', models.TextField(verbose_name='Mensaje del cliente')),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('observaciones', models.TextField(blank=True, help_text='Notas privadas para el despacho sobre este cliente.', null=True, verbose_name='Observaciones internas')),
            ],
            options={
                'verbose_name': 'Consulta de Cliente',
                'verbose_name_plural': 'Consultas de Clientes',
                'ordering': ['-fecha_contacto'],
            },
        ),
    ]
